// The JS-facing `@JS` bridge type is GENERATED by BridgeJSGen from the `// SKIP @bridge` marker on
// DemoCore.ViewModel — see Generated/ViewModelBridge.swift. No hand-written bridge lives here; this
// file only supplies the executable entry point.
#if os(WASI)

// Reactor module: JavaScript drives the generated `ViewModelBridge`; no main logic runs here.

#else

@main
struct DemoBridge {
    static func main() {
        print("DemoBridge targets WebAssembly; build it with the wasm SDK.")
    }
}

#endif
